on: [push]

jobs:
  autoformat_job:
    runs-on: ubuntu-latest
    name: Automatic formatting
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Autoformat
      id: format
      uses: bwvdnbro/skirt-format@master
    - name: Autocommit
      if: steps.format.outputs.status == 'changed'
      run: |
        git config --global user.name 'skirt-format'
        git config --global user.email 'autoformat@skirt.format'
        git commit -am "Autoformat"
        git push
